// Copyright (c) 2023 Northern Star
// 
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

// Generated by https://quicktype.io

export interface API {
    postLink:  string;
    subreddit: string;
    title:     string;
    url:       string;
    nsfw:      boolean;
    spoiler:   boolean;
    author:    string;
    ups:       number;
    preview:   string[];
}
